import os
import sys
try:os.system("git pull")
print("error")